version: '3'

services:
  api:
    build: ./backend
    ports:
      - 8082:5000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - bd
    environment:
      POSTGRES_HOST: bd

  bd:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: test
